"""Invariants of the research sufficiency gate (M1-504)."""

from __future__ import annotations

from datetime import datetime, timedelta, timezone
from typing import get_args

from hypothesis import given, strategies as st
from strategies import research_documents

from whiskeyjack_bot.research.dedup import deduplicate
from whiskeyjack_bot.research.freshness import freshness_cutoff
from whiskeyjack_bot.research.model import ResearchDocument, ResearchRun
from whiskeyjack_bot.research.packet import ResearchPacket, build_packet
from whiskeyjack_bot.research.sufficiency import SufficiencyVerdict, assess_sufficiency

NOW = datetime(2026, 8, 19, 12, 0, tzinfo=timezone.utc)
CUTOFF = freshness_cutoff(NOW, 30)
FRESH_TS = NOW
STALE_TS = NOW - timedelta(days=60)
QUESTION_ID = 42
RUNS = [
    ResearchRun(
        retrieval_run_id=run_id,
        question_id=QUESTION_ID,
        provider="asknews",
        started_at_utc=NOW,
    )
    for run_id in ("run-1", "run-2")
]
_VERDICTS = frozenset(get_args(SufficiencyVerdict))


def _packet(documents: list[ResearchDocument]) -> ResearchPacket:
    # Every document generated by research_documents() carries a retrieval_run_id
    # drawn from {"run-1", "run-2"} (strategies.RUN_IDS), so both runs are always
    # present regardless of which ids the draw happened to use. Deduplicated first,
    # the way a real packet is assembled -- the strategy can draw two documents
    # that share a dedup key, which build_packet refuses outright.
    return build_packet(QUESTION_ID, RUNS, deduplicate(documents).documents)


@given(st.lists(research_documents(), max_size=6))
def test_assess_sufficiency_never_raises_and_returns_a_member(
    documents: list[ResearchDocument],
) -> None:
    verdict = assess_sufficiency(_packet(documents), CUTOFF)
    assert verdict in _VERDICTS


def test_an_empty_packet_is_always_no_evidence() -> None:
    assert assess_sufficiency(_packet([]), CUTOFF) == "no_evidence"


@given(st.lists(research_documents(), max_size=6))
def test_a_fresh_document_added_to_any_packet_makes_it_sufficient(
    documents: list[ResearchDocument],
) -> None:
    """A single fresh document is enough regardless of what else the packet holds
    (M1-501's "one document is enough" threshold) -- so no combination of stale or
    undatable evidence drawn by the strategy can pull the verdict back down.

    ``fresh`` carries a canonical_url/content_sha256 pair outside ``strategies.py``'s
    small URL/digest pools (deliberately small, so *other* properties can exercise real
    dedup collisions) -- inside that pool, a stale draw sharing ``fresh``'s dedup key
    could survive dedup in its place and silently defeat the property, exactly the
    "vacuous strategy" trap this project's dedup properties already document.
    """
    fresh = ResearchDocument(
        retrieval_run_id="run-1",
        original_url="https://example.org/z-fresh",
        canonical_url="https://example.org/z-fresh",
        retrieved_at_utc=NOW,
        source_type="news",
        provenance="direct_api",
        content_sha256="d" * 64,
        published_at_utc=FRESH_TS,
    )
    verdict = assess_sufficiency(_packet([fresh, *documents]), CUTOFF)
    assert verdict == "sufficient"
