"""T-901 acceptance: golden schema fixtures for binary, multiple-choice and numeric records.

Backlog row: *"Add valid/invalid binary, multiple-choice and numeric records"*, acceptance
criterion *"Fixtures cover all required fields, bounds and malformed outputs."*
``CODEX_HANDOFF.md``'s "Schema tests" bullets are the literal spec this file discharges:

- valid golden records for binary, multiple-choice and numeric;
- malformed model outputs rejected;
- unknown fields either rejected or explicitly versioned.

Its fourth bullet, *"database migration from empty file is deterministic"*, is already fully
covered by ``tests/unit/test_ledger.py`` (``test_schema_is_deterministic``,
``test_migration_is_idempotent``, M1-601) and is intentionally not duplicated here.

**Authored blind** (``docs/TRACKS.md`` Wave 11's owner-split note): built only from
``CODEX_HANDOFF.md``'s test requirements, ``prompts/forecaster.md`` (the model-facing contract
``forecast/schema.py`` is transcribed from), ``questions/model.py`` (M1-201),
``forecast/schema.py`` and ``forecast/attribution.py`` (M1-402/M1-501), and
``forecast/validate.py``'s public ``output_problems`` signature. Deliberately not read:
``forecast/binary.py``, ``forecast/numeric.py``, ``forecast/multiple_choice.py`` or their test
files -- those own the type-specific bound rules (percentile-level exactness, option-set
matching, the binary prior requirement), so this suite reaches them only through
``output_problems`` and asserts a non-empty problem list, never the exact wording.

Required-field and blank-string coverage is generated by introspecting each pydantic model's
own ``model_fields`` against the golden fixture, rather than hand-picking cases -- so a field
added to a schema later is covered automatically instead of silently escaping this suite.
"""

from __future__ import annotations

import copy
import json
from collections.abc import Iterator
from pathlib import Path
from typing import Any, get_args

import pytest
import yaml
from pydantic import BaseModel, ValidationError

from whiskeyjack_bot.config import ForecastConfig, validate_config_data
from whiskeyjack_bot.forecast.attribution import AttributionFieldError
from whiskeyjack_bot.forecast.schema import (
    MAX_RATIONALE_WORDS,
    BinaryForecastResponse,
    ForecastSchemaError,
    MultipleChoiceForecastResponse,
    NumericForecastResponse,
    validate_forecast_response,
)
from whiskeyjack_bot.forecast.validate import output_problems
from whiskeyjack_bot.questions.model import (
    CanonicalBinaryQuestion,
    CanonicalMultipleChoiceQuestion,
    CanonicalNumericQuestion,
    CanonicalQuestionAdapter,
)

REPO_ROOT = Path(__file__).resolve().parents[2]
FIXTURES = Path(__file__).resolve().parents[1] / "fixtures"
QUESTION_FIXTURES = FIXTURES / "questions"
FORECAST_FIXTURES = FIXTURES / "forecasts"

# Low-entropy on purpose: CI scans every branch with gitleaks, so a realistic secret shape
# here fails unrelated PRs (see docs/LESSONS.md).
FAKE_SECRET = "privateFAKE123456"

QUESTION_TYPES: tuple[str, ...] = ("binary", "multiple_choice", "numeric")

QUESTION_MODELS: dict[str, type[Any]] = {
    "binary": CanonicalBinaryQuestion,
    "multiple_choice": CanonicalMultipleChoiceQuestion,
    "numeric": CanonicalNumericQuestion,
}

RESPONSE_MODELS: dict[str, type[Any]] = {
    "binary": BinaryForecastResponse,
    "multiple_choice": MultipleChoiceForecastResponse,
    "numeric": NumericForecastResponse,
}


def _load_json(path: Path) -> dict[str, Any]:
    data = json.loads(path.read_text(encoding="utf-8"))
    assert isinstance(data, dict)
    return data


def _question_golden(qtype: str) -> dict[str, Any]:
    return _load_json(QUESTION_FIXTURES / f"{qtype}_golden.json")


def _response_golden(qtype: str) -> dict[str, Any]:
    return _load_json(FORECAST_FIXTURES / f"{qtype}_golden.json")


def _response_sources(qtype: str) -> list[str]:
    ids = _load_json(FORECAST_FIXTURES / f"{qtype}_golden_sources.json")["source_ids"]
    assert isinstance(ids, list)
    return ids


def _committed_forecast_config() -> ForecastConfig:
    """The forecast section of the committed ``config.example.yaml``, not a hand-built one.

    A config this suite built itself could quietly drift from the range the prompt tells the
    model to respect; the committed example is the one an operator actually runs against.
    """
    data = copy.deepcopy(
        yaml.safe_load((REPO_ROOT / "config.example.yaml").read_text(encoding="utf-8"))
    )
    data["model"]["name"] = "openrouter/test-model"
    return validate_config_data(data).forecast


def _model_of(annotation: Any) -> type[BaseModel] | None:
    """The pydantic model reachable from one field annotation, if any (through Optional/list)."""
    if isinstance(annotation, type) and issubclass(annotation, BaseModel):
        return annotation
    for arg in get_args(annotation):
        found = _model_of(arg)
        if found is not None:
            return found
    return None


def _iter_required_paths(model: type[BaseModel], data: Any, prefix: str = "") -> Iterator[str]:
    """Every required-field JSON path this model declares, checked against real fixture data.

    Recurses into a nested model reached through a bare field, an ``Optional`` or a ``list`` --
    but only into a list's first item, since every item shares the same item schema and walking
    the rest would only multiply the case count, not the coverage.
    """
    if not isinstance(data, dict):
        return
    for name, field in model.model_fields.items():
        path = f"{prefix}{name}"
        if field.is_required():
            yield path
        nested_model = _model_of(field.annotation)
        if nested_model is None:
            continue
        value = data.get(name)
        if isinstance(value, dict):
            yield from _iter_required_paths(nested_model, value, prefix=f"{path}.")
        elif isinstance(value, list) and value:
            yield from _iter_required_paths(nested_model, value[0], prefix=f"{path}.0.")


def _question_required_paths(qtype: str) -> list[str]:
    return sorted(set(_iter_required_paths(QUESTION_MODELS[qtype], _question_golden(qtype))))


def _response_required_paths(qtype: str) -> list[str]:
    return sorted(set(_iter_required_paths(RESPONSE_MODELS[qtype], _response_golden(qtype))))


def _navigate(data: Any, parts: list[str]) -> tuple[Any, str]:
    node = data
    for part in parts[:-1]:
        node = node[int(part)] if part.isdigit() else node[part]
    return node, parts[-1]


def _delete_path(data: dict[str, Any], path: str) -> dict[str, Any]:
    mutated = copy.deepcopy(data)
    node, leaf = _navigate(mutated, path.split("."))
    if leaf.isdigit():
        del node[int(leaf)]
    else:
        del node[leaf]
    return mutated


def _set_path(data: dict[str, Any], path: str, value: Any) -> dict[str, Any]:
    mutated = copy.deepcopy(data)
    node, leaf = _navigate(mutated, path.split("."))
    if leaf.isdigit():
        node[int(leaf)] = value
    else:
        node[leaf] = value
    return mutated


# --- valid golden records ------------------------------------------------------------


@pytest.mark.parametrize("qtype", QUESTION_TYPES)
def test_the_golden_question_validates_and_round_trips(qtype: str) -> None:
    data = _question_golden(qtype)
    question = QUESTION_MODELS[qtype](**data)
    assert question.qtype == qtype
    again = QUESTION_MODELS[qtype].model_validate(question.model_dump(mode="json"))
    assert again == question
    assert CanonicalQuestionAdapter.validate_python(data) == question


@pytest.mark.parametrize("qtype", QUESTION_TYPES)
def test_the_golden_response_validates_and_passes_every_output_check(qtype: str) -> None:
    question = QUESTION_MODELS[qtype](**_question_golden(qtype))
    forecast = validate_forecast_response(_response_golden(qtype), RESPONSE_MODELS[qtype])
    problems = output_problems(
        forecast,
        _committed_forecast_config(),
        question=question,
        source_ids=_response_sources(qtype),
    )
    assert problems == []
    again = RESPONSE_MODELS[qtype].model_validate(forecast.model_dump(mode="json"))
    assert again == forecast


# --- required fields, introspected against the golden fixtures ------------------------


def test_the_required_field_walk_is_not_vacuous() -> None:
    """LESSONS.md's guard: an empty coverage set would make every test below pass for the
    wrong reason. Pin the load-bearing fields this suite depends on being found."""
    for qtype in QUESTION_TYPES:
        paths = set(_question_required_paths(qtype))
        assert {"question_id", "post_id", "title"} <= paths
    assert "options" in set(_question_required_paths("multiple_choice"))
    numeric_question_paths = set(_question_required_paths("numeric"))
    assert {
        "lower_bound",
        "upper_bound",
        "open_lower_bound",
        "open_upper_bound",
        "cdf_size",
    } <= numeric_question_paths

    shared_response_fields = {
        "schema_version",
        "question_id",
        "as_of_utc",
        "base_rate.reference_class",
        "base_rate.basis",
        "status_quo",
        "rationale_summary",
        "process_confidence",
        "question_type",
        "final_prediction",
    }
    for qtype in QUESTION_TYPES:
        assert shared_response_fields <= set(_response_required_paths(qtype))
    assert "final_prediction.probability_yes" in set(_response_required_paths("binary"))
    mc_response_paths = set(_response_required_paths("multiple_choice"))
    assert {
        "final_prediction.options",
        "final_prediction.options.0.option",
        "final_prediction.options.0.probability",
    } <= mc_response_paths
    numeric_response_paths = set(_response_required_paths("numeric"))
    assert {
        "final_prediction.percentiles",
        "final_prediction.percentiles.0.percentile",
        "final_prediction.percentiles.0.value",
    } <= numeric_response_paths


@pytest.mark.parametrize("qtype", QUESTION_TYPES)
def test_every_required_question_field_is_enforced(qtype: str) -> None:
    golden = _question_golden(qtype)
    paths = _question_required_paths(qtype)
    assert paths, "the walk must find at least one required field to discriminate anything"
    for path in paths:
        mutated = _delete_path(golden, path)
        with pytest.raises(ValidationError):
            QUESTION_MODELS[qtype](**mutated)


@pytest.mark.parametrize("qtype", QUESTION_TYPES)
def test_every_required_response_field_is_enforced(qtype: str) -> None:
    golden = _response_golden(qtype)
    paths = _response_required_paths(qtype)
    assert paths, "the walk must find at least one required field to discriminate anything"
    for path in paths:
        mutated = _delete_path(golden, path)
        with pytest.raises(ForecastSchemaError):
            validate_forecast_response(mutated, RESPONSE_MODELS[qtype])


# --- unknown fields ---------------------------------------------------------------------


@pytest.mark.parametrize("qtype", QUESTION_TYPES)
def test_an_unknown_field_is_rejected_on_the_question(qtype: str) -> None:
    mutated = {**_question_golden(qtype), "an_unexpected_field": "nope"}
    with pytest.raises(ValidationError):
        QUESTION_MODELS[qtype](**mutated)


@pytest.mark.parametrize("qtype", QUESTION_TYPES)
def test_an_unknown_field_is_rejected_on_the_response(qtype: str) -> None:
    mutated = {**_response_golden(qtype), "an_unexpected_field": "nope"}
    with pytest.raises(ForecastSchemaError):
        validate_forecast_response(mutated, RESPONSE_MODELS[qtype])


# --- bounds this suite can see blind, both sides -----------------------------------------


@pytest.mark.parametrize("qtype", QUESTION_TYPES)
def test_process_confidence_is_bounded_to_a_probability(qtype: str) -> None:
    golden = _response_golden(qtype)
    for ok in (0.0, 1.0):
        validate_forecast_response({**golden, "process_confidence": ok}, RESPONSE_MODELS[qtype])
    for bad in (1.0001, -0.0001, float("nan"), float("inf")):
        with pytest.raises(ForecastSchemaError):
            validate_forecast_response(
                {**golden, "process_confidence": bad}, RESPONSE_MODELS[qtype]
            )


def test_binary_probability_yes_is_bounded_to_zero_one() -> None:
    golden = _response_golden("binary")
    for ok in (0.0, 1.0):
        payload = {**golden, "final_prediction": {"probability_yes": ok}}
        validate_forecast_response(payload, BinaryForecastResponse)
    for bad in (1.0001, -0.0001, float("nan")):
        payload = {**golden, "final_prediction": {"probability_yes": bad}}
        with pytest.raises(ForecastSchemaError):
            validate_forecast_response(payload, BinaryForecastResponse)


def test_multiple_choice_option_probability_is_bounded_to_zero_one() -> None:
    golden = _response_golden("multiple_choice")
    options = golden["final_prediction"]["options"]
    for bad in (1.0001, -0.0001, float("nan")):
        mutated_options = [dict(options[0], probability=bad), *options[1:]]
        payload = {**golden, "final_prediction": {"options": mutated_options}}
        with pytest.raises(ForecastSchemaError):
            validate_forecast_response(payload, MultipleChoiceForecastResponse)


def test_numeric_percentile_level_is_bounded_to_zero_one() -> None:
    golden = _response_golden("numeric")
    percentiles = golden["final_prediction"]["percentiles"]
    for bad in (1.0001, -0.0001, float("nan")):
        mutated = [dict(percentiles[0], percentile=bad), *percentiles[1:]]
        payload = {**golden, "final_prediction": {"percentiles": mutated}}
        with pytest.raises(ForecastSchemaError):
            validate_forecast_response(payload, NumericForecastResponse)


def test_numeric_question_bounds_must_be_strictly_ordered() -> None:
    golden = _question_golden("numeric")
    CanonicalNumericQuestion(**{**golden, "lower_bound": 0.0, "upper_bound": 1.0})
    for bad_upper in (golden["lower_bound"], golden["lower_bound"] - 1.0):
        with pytest.raises(ValidationError):
            CanonicalNumericQuestion(**{**golden, "upper_bound": bad_upper})


def test_multiple_choice_options_need_at_least_two() -> None:
    golden = _question_golden("multiple_choice")
    CanonicalMultipleChoiceQuestion(**{**golden, "options": ["A", "B"]})
    with pytest.raises(ValidationError):
        CanonicalMultipleChoiceQuestion(**{**golden, "options": ["Only one"]})


def test_multiple_choice_options_must_be_distinct_and_non_blank() -> None:
    golden = _question_golden("multiple_choice")
    with pytest.raises(ValidationError):
        CanonicalMultipleChoiceQuestion(**{**golden, "options": ["A", "A"]})
    with pytest.raises(ValidationError):
        CanonicalMultipleChoiceQuestion(**{**golden, "options": ["A", "   "]})


@pytest.mark.parametrize("qtype", QUESTION_TYPES)
def test_rationale_summary_word_cap_is_enforced(qtype: str) -> None:
    golden = _response_golden(qtype)
    at_cap = " ".join("word" for _ in range(MAX_RATIONALE_WORDS))
    validate_forecast_response({**golden, "rationale_summary": at_cap}, RESPONSE_MODELS[qtype])
    over_cap = " ".join("word" for _ in range(MAX_RATIONALE_WORDS + 1))
    with pytest.raises(ForecastSchemaError):
        validate_forecast_response(
            {**golden, "rationale_summary": over_cap}, RESPONSE_MODELS[qtype]
        )


@pytest.mark.parametrize("qtype", QUESTION_TYPES)
@pytest.mark.parametrize(
    "path", ["status_quo", "rationale_summary", "base_rate.reference_class", "base_rate.basis"]
)
def test_shared_nonblank_fields_reject_a_blank_value(qtype: str, path: str) -> None:
    golden = _response_golden(qtype)
    mutated = _set_path(golden, path, "   ")
    with pytest.raises(ForecastSchemaError):
        validate_forecast_response(mutated, RESPONSE_MODELS[qtype])


# --- malformed outputs beyond missing/extra/bounds -----------------------------------------


@pytest.mark.parametrize("qtype", QUESTION_TYPES)
def test_wrong_schema_version_is_rejected(qtype: str) -> None:
    golden = _response_golden(qtype)
    with pytest.raises(ForecastSchemaError):
        validate_forecast_response({**golden, "schema_version": "0.9.0"}, RESPONSE_MODELS[qtype])


@pytest.mark.parametrize("qtype", QUESTION_TYPES)
def test_reasoning_strategy_tags_must_not_repeat(qtype: str) -> None:
    golden = _response_golden(qtype)
    mutated = {**golden, "reasoning_strategy_tags": ["base_rate", "base_rate"]}
    with pytest.raises(ForecastSchemaError):
        validate_forecast_response(mutated, RESPONSE_MODELS[qtype])


@pytest.mark.parametrize("qtype", ("multiple_choice", "numeric"))
def test_a_non_binary_response_rejects_a_supplied_prior(qtype: str) -> None:
    golden = _response_golden(qtype)
    with pytest.raises(ForecastSchemaError):
        validate_forecast_response({**golden, "model_prior": 0.5}, RESPONSE_MODELS[qtype])
    mutated = {**golden, "base_rate": {**golden["base_rate"], "prior_probability": 0.5}}
    with pytest.raises(ForecastSchemaError):
        validate_forecast_response(mutated, RESPONSE_MODELS[qtype])


def test_output_problems_refuses_a_source_ids_argument_of_the_wrong_shape() -> None:
    """``attribution.py``'s own docstring names this: a bare string satisfies ``Sequence[str]``
    and would silently mean "the ids are each one character of this string"."""
    forecast = validate_forecast_response(_response_golden("binary"), BinaryForecastResponse)
    question = CanonicalBinaryQuestion(**_question_golden("binary"))
    with pytest.raises(AttributionFieldError):
        output_problems(
            forecast, _committed_forecast_config(), question=question, source_ids="src-001"
        )


def test_a_repeated_source_id_in_one_citation_list_is_rejected() -> None:
    golden = _response_golden("binary")
    mutated = {**golden, "base_rate": {**golden["base_rate"], "source_ids": ["src-001", "src-001"]}}
    forecast = validate_forecast_response(mutated, BinaryForecastResponse)
    question = CanonicalBinaryQuestion(**_question_golden("binary"))
    problems = output_problems(
        forecast,
        _committed_forecast_config(),
        question=question,
        source_ids=_response_sources("binary"),
    )
    assert any("must not repeat a source_id" in problem for problem in problems)


def test_citing_an_id_never_supplied_is_rejected() -> None:
    golden = _response_golden("binary")
    mutated = {**golden, "base_rate": {**golden["base_rate"], "source_ids": ["src-999"]}}
    forecast = validate_forecast_response(mutated, BinaryForecastResponse)
    question = CanonicalBinaryQuestion(**_question_golden("binary"))
    problems = output_problems(
        forecast,
        _committed_forecast_config(),
        question=question,
        source_ids=_response_sources("binary"),
    )
    assert any("must name only source_ids supplied" in problem for problem in problems)


def test_no_problem_string_echoes_the_offending_citation() -> None:
    golden = _response_golden("binary")
    mutated = {
        **golden,
        "base_rate": {**golden["base_rate"], "source_ids": [FAKE_SECRET]},
    }
    forecast = validate_forecast_response(mutated, BinaryForecastResponse)
    question = CanonicalBinaryQuestion(**_question_golden("binary"))
    problems = output_problems(
        forecast,
        _committed_forecast_config(),
        question=question,
        source_ids=_response_sources("binary"),
    )
    assert problems, "the unresolvable citation must bite for this to discriminate anything"
    assert not any(FAKE_SECRET in problem for problem in problems)


# --- type-specific bounds, reached only through output_problems (blind-authorship boundary) --


def test_a_multiple_choice_bound_violation_is_caught_by_the_composed_entry_point() -> None:
    """Owned by ``forecast/multiple_choice.py``, not read on this branch: asserted as a
    non-empty result only, never by message text."""
    payload = {
        **_response_golden("multiple_choice"),
        "final_prediction": {"options": [{"option": "Not a real option", "probability": 1.0}]},
    }
    forecast = validate_forecast_response(payload, MultipleChoiceForecastResponse)
    question = CanonicalMultipleChoiceQuestion(**_question_golden("multiple_choice"))
    problems = output_problems(
        forecast,
        _committed_forecast_config(),
        question=question,
        source_ids=_response_sources("multiple_choice"),
    )
    assert problems


def test_a_numeric_bound_violation_is_caught_by_the_composed_entry_point() -> None:
    """Owned by ``forecast/numeric.py``, not read on this branch: asserted as a non-empty
    result only, never by message text."""
    payload = {
        **_response_golden("numeric"),
        "final_prediction": {"percentiles": [{"percentile": 0.5, "value": 24.0}]},
    }
    forecast = validate_forecast_response(payload, NumericForecastResponse)
    question = CanonicalNumericQuestion(**_question_golden("numeric"))
    problems = output_problems(
        forecast,
        _committed_forecast_config(),
        question=question,
        source_ids=_response_sources("numeric"),
    )
    assert problems


def test_a_priorless_binary_response_is_caught_by_the_composed_entry_point() -> None:
    """Owned by ``forecast/binary.py``, not read on this branch: asserted as a non-empty
    result only, never by message text."""
    golden = _response_golden("binary")
    payload = {
        **golden,
        "model_prior": None,
        "base_rate": {**golden["base_rate"], "prior_probability": None},
    }
    forecast = validate_forecast_response(payload, BinaryForecastResponse)
    question = CanonicalBinaryQuestion(**_question_golden("binary"))
    problems = output_problems(
        forecast,
        _committed_forecast_config(),
        question=question,
        source_ids=_response_sources("binary"),
    )
    assert problems
